# Generated by Django 5.1.2 on 2024-10-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_app', '0002_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
    ]
