# Generated by Django 5.1.2 on 2024-10-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_app', '0004_expense_created_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
